targets:
  $default:
    sources:
      exclude:
        - ios/.symlinks
        - ios/.symlinks/**/**.dart
    builders:
      go_router_extra_codec_generator:
        enabled: true
        options:
          output_filename: router_extra_converter.dart
          output_folder: lib/generated/router
          codec_class_name: MyRouterExtraCodec
          generate_for:
            include:
              - lib/main.dart
            exclude:
              - lib/**/*.g.dart
              - lib/**/*.freezed.dart
              - lib/generated/**
      json_serializable:
        options:
          explicit_to_json: true
          checked: true
        generate_for:
          include:
            - lib/main.dart

global_options:
  json_serializable:
    runs_before:
      - go_router_extra_codec_generator

builders:
  go_router_extra_codec_generator:
    import: "package:go_router_extra_codec_generator/builder.dart"
    builder_factories:
      - goRouterExtraCodecBuilder
    build_extensions:
      $lib$:
        - lib/generated/router/router_extra_converter.dart
    auto_apply: dependents
    build_to: source
